#! /usr/bin/env bash
#
# Checks the current repository and all if its submodules for being
# in "release shape".

check_cmd='
test -e CHANGES && (
    printf "%20s: " " `basename \`git config --get remote.origin.url\``";
    printf "%-25s " " `update-changes -c`"; 
    printf "VERSION: %-10s  " `cat VERSION`;
    printf "tags: %s" "`git tag -l --contains HEAD | sort -r | paste -sd \" \"`";
    echo;
    )'

eval $check_cmd
git submodule foreach -q --recursive "$check_cmd; true"
