#!/usr/bin/env ruby

cvsroot = ':pserver:anonymous@cvs-mirror.mozilla.org:/cvsroot';
certdata = 'mozilla/security/nss/lib/ckfw/builtins/certdata.txt';

incert=false
intrust=false
io = IO.popen("cvs -d #{cvsroot} co -p #{certdata}")

puts "# Don't edit!  This file is automatically generated."
puts "# Generated at: #{Time.now}"
puts "@load ssl"
puts "module SSL;";
puts "redef root_certs += {";

all_certs = []

cert_name = ""
cert = ""
io.each do |line|
  line.chomp!
  if intrust
    if line =~ /^CKA_TRUST_SERVER_AUTH/
      if line =~ /CKT_NSS_TRUSTED_DELEGATOR/
        puts "	[\"#{cert_name}\"] = \"#{cert}\","
      end
      intrust=false
    end
  else
    if line =~ /^CKA_LABEL/
      cert_name = line.sub(/.*\"(.*)\".*/, "\\1")
      i = 0
      while all_certs.include?(cert_name)
        i+=1
        cert_name += " #{i}"
      end
      all_certs << cert_name
    elsif line =~ /^CKA_VALUE MULTILINE_OCTAL/
      incert=true
      cert=""
    elsif line =~ /^CKA_CLASS CK_OBJECT_CLASS CKO_NSS_TRUST/
      intrust=true
    elsif line =~ /^END/
      incert=false
    elsif incert
      cert += line.split(/\\/).collect { |x| x.oct.chr.unpack("H2")[0].upcase if x!="" }.join("\\x")
    end
  end
end
puts "};"
