ci_template: &CI_TEMPLATE
  only_if: >
    $CIRRUS_PR != '' ||
    ( $CIRRUS_REPO_OWNER == 'zeek' && $CIRRUS_BRANCH == 'master' )

  sync_submodules_script: git submodule update --recursive --init

  build_script: ./ci/run-ci build
  test_script: ./ci/run-ci test

  on_failure:
    upload_btest_tmp_dir_artifacts:
      path: "testing/tmp.tar.gz"

# Linux EOL timelines: https://linuxlifecycle.com/
# Fedora (~13 months): https://fedoraproject.org/wiki/Fedora_Release_Life_Cycle

fedora42_task:
  container:
    # Fedora 42 EOL: Around May 2026
    dockerfile: ci/fedora-42/Dockerfile
  << : *CI_TEMPLATE

fedora41_task:
  container:
    # Fedora 41 EOL: Around Nov 2025
    dockerfile: ci/fedora-41/Dockerfile
  << : *CI_TEMPLATE

centosstream9_task:
  container:
    # Stream 9 EOL: Around Dec 2027
    dockerfile: ci/centos-stream-9/Dockerfile
  << : *CI_TEMPLATE

debian12_task:
  container:
    # Debian 12 EOL: TBD
    dockerfile: ci/debian-12/Dockerfile
  << : *CI_TEMPLATE

debian11_task:
  container:
    # Debian 11 EOL: June 2026
    dockerfile: ci/debian-11/Dockerfile
  << : *CI_TEMPLATE

opensuse_leap_15_5_task:
  container:
    # Opensuse Leap 15.5 EOL: Around Dec 25
    dockerfile: ci/opensuse-leap-15.5/Dockerfile
  << : *CI_TEMPLATE

opensuse_leap_15_6_task:
  container:
    # Opensuse Leap 15.6 EOL: ~Dec 2025
    dockerfile: ci/opensuse-leap-15.6/Dockerfile
  << : *CI_TEMPLATE

opensuse_tumbleweed_task:
  container:
    # Opensuse Tumbleweed has no EOL
    dockerfile: ci/opensuse-tumbleweed/Dockerfile
  prepare_script: ./ci/opensuse-tumbleweed/prepare.sh
  << : *CI_TEMPLATE

ubuntu24_10_task:
  container:
    # Ubuntu 24.10 EOL: 2025-07-30
    dockerfile: ci/ubuntu-24.10/Dockerfile
  << : *CI_TEMPLATE

ubuntu24_task:
  container:
    # Ubuntu 24.04 EOL: Jun 2029
    dockerfile: ci/ubuntu-24.04/Dockerfile
  << : *CI_TEMPLATE

ubuntu22_task:
  container:
    # Ubuntu 22.04 EOL: April 2027
    dockerfile: ci/ubuntu-22.04/Dockerfile
  << : *CI_TEMPLATE

# Cirrus currently only supports running on Sonoma.
macos_sonoma_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sonoma
  prepare_script: ./ci/macos/prepare.sh
  << : *CI_TEMPLATE

# FreeBSD EOL timelines: https://www.freebsd.org/security/#sup
freebsd14_task:
  freebsd_instance:
    # FreeBSD 14 EOL: Nov 30 2028
    image_family: freebsd-14-2
  prepare_script: ./ci/freebsd/prepare.sh
  << : *CI_TEMPLATE

freebsd13_task:
  freebsd_instance:
    # FreeBSD 13 EOL: January 31, 2026
    image_family: freebsd-13-4
  prepare_script: ./ci/freebsd/prepare.sh
  << : *CI_TEMPLATE
