# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
repos:
- repo: https://github.com/maxwinterstein/shfmt-py
  rev: v3.11.0.2
  hooks:
    - id: shfmt
      args: ["-w", "-i", "4", "-ci"]
