#! /usr/bin/env bash

function abspath
{
    (cd "$1"; pwd)
}

function relpath
{
    echo "$1" | sed "s#`pwd`/\{0,1\}##g"
}

function lower
{
    echo "$1" | tr A-Z a-z
}

function init-skeleton
{
    for i in `cd ${skeleton} && find * -type d`; do
        mkdir -p `echo ${plugin_src}/$i`
    done

    for i in `cd ${skeleton} && find * -type f -not -name '.*'`; do
        src=${skeleton}/$i
        dst=`echo ${plugin_src}/$i`
        dst=`echo $dst | sed "s#%NS\\.#${plugin_ns_lower}/#g"`
        dst=`echo $dst | sed "s#%NAME\\.#${plugin_name_lower}/#g"`

        tmp=$dst.$$.tmp

        mkdir -p `dirname ${dst}`
        cat ${src} \
            | sed "s/@PLUGIN_NAME@/${plugin_name}/g" \
            | sed "s/@PLUGIN_NAMESPACE@/${plugin_ns}/g" \
            >${tmp}

        if [ -e ${dst} ]; then
            cmp -s ${tmp} ${dst} || echo "`relpath ${dst}` exists, not installing new version"
            rm -f ${tmp}
            continue
        fi

        echo Installing `relpath ${dst}` ...
        mv ${tmp} ${dst}

    done
}

if [ $# != 2 ]; then
    echo "Usage: `basename $0` <namespace> <plugin name>"
    exit 1
fi

skeleton=`dirname $0`/skeleton
plugin_ns=$1
plugin_name=$2
plugin_ns_lower=`lower $1`
plugin_name_lower=`lower $2`
plugin_src=`pwd`
plugin_build=`pwd`/dylib

init-skeleton
